name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v31
      - run: make build
